version: "3.8"

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chaboq_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  

  # celery_worker:
  #   build: .
  #   command: celery -A core worker --pool=solo --loglevel=info
  #   volumes:
  #     - .:/app
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=core.settings
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - PYTHONUNBUFFERED=1
  #   depends_on:
  #     - redis
  #     - db

volumes:
  postgres_data:
  redis_data: