version: "3.8"

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chaboq_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  

  celery_worker:
    build: .
    command: celery -A src.config.celery worker --loglevel=info
    depends_on:
      - redis

  flower:
    image: mher/flower:latest
    command: ["celery", "flower", "--broker=redis://redis:6379", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data: